name: C++ build
on: [push]

jobs:
  changes:
    uses: ./.github/workflows/filter.yaml

  build_cpp:
    needs: changes
    if: ${{ needs.changes.outputs.algorithmic == 'true' }}

    runs-on: ubuntu-latest

    container:
      image: joennlae/halutmatmul-ci:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build C++
      run: |
        cd maddness/cpp
        ./build.sh