name: Linting

on: push

jobs:

  lint_python:
    name: Python Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Lint with pylint
      run: |
        $CONDA/bin/conda install pylint
        $CONDA/bin/pylint --rcfile=.pylintrc --reports yes maddness/python/* src/*
