name: MyPy
# https://autobencoder.com/2020-08-24-conda-actions/
on: [push]

jobs:
  python_typechecking:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Test with pytest
      run: |
        $CONDA/bin/conda install mypy
        $CONDA/bin/mypy
