name: PyTest
# https://autobencoder.com/2020-08-24-conda-actions/
on: [push]

jobs:
  test_python:
    strategy:
      matrix:
        split: [1, 2, 3]
    runs-on: ubuntu-latest
    container:
      image: joennlae/halutmatmul-conda-gpu:latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v2
    - name: Download Test data
      run: |
        apt-get -y update
        apt-get -y install curl
        cd maddness && bash ./download_assets.sh && cd ..
    - name: Test with pytest
      run: |
        source /venv/bin/activate
        pip install pytest-split
        pytest -srPA -k "not gpu" --splits 3 --group ${{ matrix.split }}
