name: MyPy
# https://autobencoder.com/2020-08-24-conda-actions/
on: [push]

jobs:
  python_typechecking:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        CONDA_OVERRIDE_GLIBC=2.17 #https://github.com/conda/conda/issues/11204#issuecomment-1039839191
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Check types with mypy
      run: |
        $CONDA/bin/conda install -c conda-forge mypy=0.942
        yes | $CONDA/bin/mypy --install-types
        $CONDA/bin/mypy --config-file .mypy.ini --pretty 
